CREATE TABLE `BOOKMARK`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `Link` varchar(100) NOT NULL,
    `Title` text,
    `Publisher` text,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `Link` (`Link`)

);

CREATE TABLE `TAG`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `Title` varchar(2000) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (`id`),
    UNIQUE KEY `Title` (`Title`)
);



CREATE TABLE `TAGSOFBOOK`(
    `BOOKMARKID` INT NOT NULL,
    `TAGID` INT NOT NULL,
    PRIMARY KEY(`BOOKMARKID`,`TAGID`),
    FOREIGN KEY (`BOOKMARKID`) REFERENCES `BOOKMARK` (`id`),
    FOREIGN KEY (`TAGID`) REFERENCES `TAG` (`id`)

);


